services:
  webapp:
    build: ./webapp
    ports:
     - "80:80"
    depends_on:
      - database
  
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    ports:
      - "3306:3306"